###Plotting Marginal Effects of the Forward, Reverse, and Claassen Indices (Broad Index with Bad Completes)
##July 19, 2023
#Last Updated: Kendra Pinegar; July 19, 2023

#Load the datasets and packages in
library(sjPlot)
library(readxl)
m_dem <- read_excel("MX_Data_7.6.23.xlsx")
p_dem <- read_excel("PE_Data_6.26.23.xlsx")

##NOTE: Run the cleaning codes before you run these codes (DO run non-takers cleaning code, do NOT run bad completes)

#Recoded questions indices, Reverse Index
m_dem$reverse_index <- rowMeans(m_dem[, c("frexp2_recode", "frassc1_recode", "frassc3_recode", "unisuff1_recode", "decelec1_recode", "frelect2_recode", "judcnstr2_recode", "legcnstr1_recode", "eqlaw1_recode")], na.rm = TRUE)

p_dem$reverse_index <- rowMeans(p_dem[, c("frexp2_recode", "frassc1_recode", "frassc3_recode", "unisuff1_recode", "decelec1_recode", "frelect2_recode", "judcnstr2_recode", "legcnstr1_recode", "eqlaw1_recode")], na.rm = TRUE)

#Not recoded questions indices, Forward Index
m_dem$forward_index <- rowMeans(m_dem[, c("frexp1", "frassc2", "unisuff2", "decelec2", "frelect1", "judcnstr1", "legcnstr2", "eqlaw2")], na.rm = TRUE)

p_dem$forward_index <- rowMeans(p_dem[, c("frexp1", "frassc2", "unisuff2", "decelec2", "frelect1", "judcnstr1", "legcnstr2", "eqlaw2")], na.rm = TRUE)

#Claassen 7 question indices, Claassen Index
m_dem$claassen_index <- rowMeans(m_dem[, c("frexp2_recode", "frassc1_recode", "unisuff2", "frelect2_recode", "judcnstr2_recode", "legcnstr1_recode", "eqlaw1_recode")], na.rm = TRUE)

p_dem$claassen_index <- rowMeans(p_dem[, c("frexp2_recode", "frassc1_recode", "unisuff2", "frelect2_recode", "judcnstr2_recode", "legcnstr1_recode", "eqlaw1_recode")], na.rm = TRUE)

#17-question indices, Main Index
m_dem$main_index <- rowMeans(m_dem[, c("frexp1", "frexp2_recode", "frassc1_recode", "frassc2", "frassc3_recode", "unisuff1_recode", "unisuff2", "decelec1_recode", "decelec2", "frelect1", "frelect2_recode", "judcnstr1", "legcnstr2", "eqlaw2", "judcnstr2_recode", "legcnstr1_recode", "eqlaw1_recode")], na.rm = TRUE)

p_dem$main_index <- rowMeans(p_dem[, c("frexp1", "frexp2_recode", "frassc1_recode", "frassc2", "frassc3_recode", "unisuff1_recode", "unisuff2", "decelec1_recode", "decelec2", "frelect1", "frelect2_recode", "judcnstr1", "legcnstr2", "eqlaw2", "judcnstr2_recode", "legcnstr1_recode", "eqlaw1_recode")], na.rm = TRUE)

#Interactions with moderators; controls: age, gender_n, income_n, ideo_1
###MEXICO###
#Mexico- reverse_index
summary(int_pres_index1_mex <- lm(reverse_index~treat*pres+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_pres_index1_mex, type = "pred", terms = "pres")
summary(int_persecon_index1_mex <- lm(reverse_index~treat*pers_econ+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_persecon_index1_mex, type = "pred", terms = "pers_econ")
summary(int_persvio_index1_mex <- lm(reverse_index~treat*pers_vio+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_persvio_index1_mex, type = "pred", terms = "pers_vio")
summary(int_countecon_index1_mex <- lm(reverse_index~treat*count_econ_recode+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_countecon_index1_mex, type = "pred", terms = "count_econ_recode")
summary(int_countvio_index1_mex <- lm(reverse_index~treat*count_vio_recode+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_countvio_index1_mex, type = "pred", terms = "count_vio_recode")
summary(int_polit_index1_mex <- lm(reverse_index~treat*politpart+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_polit_index1_mex, type = "pred", terms = "politpart")
summary(int_elite_index1_mex <- lm(reverse_index~treat*elite_recode+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_elite_index1_mex, type = "pred", terms = "elite_recode")

#Mexico- forward_index
summary(int_pres_index2_mex <- lm(forward_index~treat*pres+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_pres_index2_mex, type = "pred", terms = "pres")
summary(int_persecon_index2_mex <- lm(forward_index~treat*pers_econ+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_persecon_index2_mex, type = "pred", terms = "pers_econ")
summary(int_persvio_index2_mex <- lm(forward_index~treat*pers_vio+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_persvio_index2_mex, type = "pred", terms = "pers_vio")
summary(int_countecon_index2_mex <- lm(forward_index~treat*count_econ_recode+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_countecon_index2_mex, type = "pred", terms = "count_econ_recode")
summary(int_countvio_index2_mex <- lm(forward_index~treat*count_vio_recode+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_countvio_index2_mex, type = "pred", terms = "count_vio_recode")
summary(int_polit_index2_mex <- lm(forward_index~treat*politpart+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_polit_index2_mex, type = "pred", terms = "politpart")
summary(int_elite_index2_mex <- lm(forward_index~treat*elite_recode+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_elite_index2_mex, type = "pred", terms = "elite_recode")

#Mexico- claassen_index
summary(int_pres_index3_mex <- lm(claassen_index~treat*pres+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_pres_index3_mex, type = "pred", terms = "pres")
summary(int_persecon_index3_mex <- lm(claassen_index~treat*pers_econ+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_persecon_index3_mex, type = "pred", terms = "pers_econ")
summary(int_persvio_index3_mex <- lm(claassen_index~treat*pers_vio+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_persvio_index3_mex, type = "pred", terms = "pers_vio")
summary(int_countecon_index3_mex <- lm(claassen_index~treat*count_econ_recode+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_countecon_index3_mex, type = "pred", terms = "count_econ_recode")
summary(int_countvio_index3_mex <- lm(claassen_index~treat*count_vio_recode+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_countvio_index3_mex, type = "pred", terms = "count_vio_recode")
summary(int_polit_index3_mex <- lm(claassen_index~treat*politpart+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_polit_index3_mex, type = "pred", terms = "politpart")
summary(int_elite_index3_mex <- lm(claassen_index~treat*elite_recode+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_elite_index3_mex, type = "pred", terms = "elite_recode")

#Mexico- main_index
summary(int_pres_main_mex <- lm(main_index~treat*pres+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_pres_main_mex, type = "pred", terms = "pres")
summary(int_persecon_main_mex <- lm(main_index~treat*pers_econ+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_persecon_main_mex, type = "pred", terms = "pers_econ")
summary(int_persvio_main_mex <- lm(main_index~treat*pers_vio+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_persvio_main_mex, type = "pred", terms = "pers_vio")
summary(int_countecon_main_mex <- lm(main_index~treat*count_econ_recode+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_countecon_main_mex, type = "pred", terms = "count_econ_recode")
summary(int_countvio_main_mex <- lm(main_index~treat*count_vio_recode+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_countvio_main_mex, type = "pred", terms = "count_vio_recode")
summary(int_polit_main_mex <- lm(main_index~treat*politpart+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_polit_main_mex, type = "pred", terms = "politpart")
summary(int_elite_main_mex <- lm(main_index~treat*elite_recode+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_elite_main_mex, type = "pred", terms = "elite_recode")

#Change all variables to factors (so we can see the separate effects at each level)
m_dem$pres=as.factor(m_dem$pres)
m_dem$pers_econ=as.factor(m_dem$pers_econ)
m_dem$pers_vio=as.factor(m_dem$pers_vio)
m_dem$count_econ_recode=as.factor(m_dem$count_econ_recode)
m_dem$count_vio_recode=as.factor(m_dem$count_vio_recode)
m_dem$politpart=as.factor(m_dem$politpart)
m_dem$elite_recode=as.factor(m_dem$elite_recode)

#Mexico- reverse_index (separate effects)
summary(int_pres_index1_mex <- lm(reverse_index~treat*pres+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_pres_index1_mex, type = "pred", terms = "pres")
summary(int_persecon_index1_mex <- lm(reverse_index~treat*pers_econ+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_persecon_index1_mex, type = "pred", terms = "pers_econ")
summary(int_persvio_index1_mex <- lm(reverse_index~treat*pers_vio+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_persvio_index1_mex, type = "pred", terms = "pers_vio")
summary(int_countecon_index1_mex <- lm(reverse_index~treat*count_econ_recode+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_countecon_index1_mex, type = "pred", terms = "count_econ_recode")
summary(int_countvio_index1_mex <- lm(reverse_index~treat*count_vio_recode+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_countvio_index1_mex, type = "pred", terms = "count_vio_recode")
summary(int_polit_index1_mex <- lm(reverse_index~treat*politpart+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_polit_index1_mex, type = "pred", terms = "politpart")
summary(int_elite_index1_mex <- lm(reverse_index~treat*elite_recode+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_elite_index1_mex, type = "pred", terms = "elite_recode")

#Mexico- forward_index (separate effects)
summary(int_pres_index2_mex <- lm(forward_index~treat*pres+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_pres_index2_mex, type = "pred", terms = "pres")
summary(int_persecon_index2_mex <- lm(forward_index~treat*pers_econ+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_persecon_index2_mex, type = "pred", terms = "pers_econ")
summary(int_persvio_index2_mex <- lm(forward_index~treat*pers_vio+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_persvio_index2_mex, type = "pred", terms = "pers_vio")
summary(int_countecon_index2_mex <- lm(forward_index~treat*count_econ_recode+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_countecon_index2_mex, type = "pred", terms = "count_econ_recode")
summary(int_countvio_index2_mex <- lm(forward_index~treat*count_vio_recode+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_countvio_index2_mex, type = "pred", terms = "count_vio_recode")
summary(int_polit_index2_mex <- lm(forward_index~treat*politpart+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_polit_index2_mex, type = "pred", terms = "politpart")
summary(int_elite_index2_mex <- lm(forward_index~treat*elite_recode+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_elite_index2_mex, type = "pred", terms = "elite_recode")

#Mexico- claassen_index (separate effects)
summary(int_pres_index3_mex <- lm(claassen_index~treat*pres+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_pres_index3_mex, type = "pred", terms = "pres")
summary(int_persecon_index3_mex <- lm(claassen_index~treat*pers_econ+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_persecon_index3_mex, type = "pred", terms = "pers_econ")
summary(int_persvio_index3_mex <- lm(claassen_index~treat*pers_vio+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_persvio_index3_mex, type = "pred", terms = "pers_vio")
summary(int_countecon_index3_mex <- lm(claassen_index~treat*count_econ_recode+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_countecon_index3_mex, type = "pred", terms = "count_econ_recode")
summary(int_countvio_index3_mex <- lm(claassen_index~treat*count_vio_recode+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_countvio_index3_mex, type = "pred", terms = "count_vio_recode")
summary(int_polit_index3_mex <- lm(claassen_index~treat*politpart+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_polit_index3_mex, type = "pred", terms = "politpart")
summary(int_elite_index3_mex <- lm(claassen_index~treat*elite_recode+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_elite_index3_mex, type = "pred", terms = "elite_recode")

#Mexico- main_index (separate effects)
summary(int_pres_main_mex <- lm(main_index~treat*pres+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_pres_main_mex, type = "pred", terms = "pres")
summary(int_persecon_main_mex <- lm(main_index~treat*pers_econ+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_persecon_main_mex, type = "pred", terms = "pers_econ")
summary(int_persvio_main_mex <- lm(main_index~treat*pers_vio+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_persvio_main_mex, type = "pred", terms = "pers_vio")
summary(int_countecon_main_mex <- lm(main_index~treat*count_econ_recode+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_countecon_main_mex, type = "pred", terms = "count_econ_recode")
summary(int_countvio_main_mex <- lm(main_index~treat*count_vio_recode+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_countvio_main_mex, type = "pred", terms = "count_vio_recode")
summary(int_polit_main_mex <- lm(main_index~treat*politpart+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_polit_main_mex, type = "pred", terms = "politpart")
summary(int_elite_main_mex <- lm(main_index~treat*elite_recode+age+gender_n+income_n+ideo_1, data=m_dem))
plot_model(int_elite_main_mex, type = "pred", terms = "elite_recode")

###PERU###

#Peru- reverse_index
summary(int_pres_index1_per <- lm(reverse_index~treat*pres+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_pres_index1_per, type = "pred", terms = "pres")
summary(int_persecon_index1_per <- lm(reverse_index~treat*pers_econ+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_persecon_index1_per, type = "pred", terms = "pers_econ")
summary(int_persvio_index1_per <- lm(reverse_index~treat*pers_vio+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_persvio_index1_per, type = "pred", terms = "pers_vio")
summary(int_countecon_index1_per <- lm(reverse_index~treat*count_econ_recode+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_countecon_index1_per, type = "pred", terms = "count_econ_recode")
summary(int_countvio_index1_per <- lm(reverse_index~treat*count_vio_recode+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_countvio_index1_per, type = "pred", terms = "count_vio_recode")
summary(int_polit_index1_per <- lm(reverse_index~treat*politpart+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_polit_index1_per, type = "pred", terms = "politpart")
summary(int_elite_index1_per <- lm(reverse_index~treat*elite_recode+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_elite_index1_per, type = "pred", terms = "elite_recode")

#Peru- forward_index
summary(int_pres_index2_per <- lm(forward_index~treat*pres+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_pres_index2_per, type = "pred", terms = "pres")
summary(int_persecon_index2_per <- lm(forward_index~treat*pers_econ+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_persecon_index2_per, type = "pred", terms = "pers_econ")
summary(int_persvio_index2_per <- lm(forward_index~treat*pers_vio+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_persvio_index2_per, type = "pred", terms = "pers_vio")
summary(int_countecon_index2_per <- lm(forward_index~treat*count_econ_recode+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_countecon_index2_per, type = "pred", terms = "count_econ_recode")
summary(int_countvio_index2_per <- lm(forward_index~treat*count_vio_recode+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_countvio_index2_per, type = "pred", terms = "count_vio_recode")
summary(int_polit_index2_per <- lm(forward_index~treat*politpart+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_polit_index2_per, type = "pred", terms = "politpart")
summary(int_elite_index2_per <- lm(forward_index~treat*elite_recode+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_elite_index2_per, type = "pred", terms = "elite_recode")

#Peru- claassen_index
summary(int_pres_index3_per <- lm(claassen_index~treat*pres+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_pres_index3_per, type = "pred", terms = "pres")
summary(int_persecon_index3_per <- lm(claassen_index~treat*pers_econ+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_persecon_index3_per, type = "pred", terms = "pers_econ")
summary(int_persvio_index3_per <- lm(claassen_index~treat*pers_vio+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_persvio_index3_per, type = "pred", terms = "pers_vio")
summary(int_countecon_index3_per <- lm(claassen_index~treat*count_econ_recode+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_countecon_index3_per, type = "pred", terms = "count_econ_recode")
summary(int_countvio_index3_per <- lm(claassen_index~treat*count_vio_recode+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_countvio_index3_per, type = "pred", terms = "count_vio_recode")
summary(int_polit_index3_per <- lm(claassen_index~treat*politpart+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_polit_index3_per, type = "pred", terms = "politpart")
summary(int_elite_index3_per <- lm(claassen_index~treat*elite_recode+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_elite_index3_per, type = "pred", terms = "elite_recode")

#Peru- main_index
summary(int_pres_main_per <- lm(main_index~treat*pres+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_pres_main_per, type = "pred", terms = "pres")
summary(int_persecon_main_per <- lm(main_index~treat*pers_econ+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_persecon_main_per, type = "pred", terms = "pers_econ")
summary(int_persvio_main_per <- lm(main_index~treat*pers_vio+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_persvio_main_per, type = "pred", terms = "pers_vio")
summary(int_countecon_main_per <- lm(main_index~treat*count_econ_recode+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_countecon_main_per, type = "pred", terms = "count_econ_recode")
summary(int_countvio_main_per <- lm(main_index~treat*count_vio_recode+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_countvio_main_per, type = "pred", terms = "count_vio_recode")
summary(int_polit_main_per <- lm(main_index~treat*politpart+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_polit_main_per, type = "pred", terms = "politpart")
summary(int_elite_main_per <- lm(main_index~treat*elite_recode+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_elite_main_per, type = "pred", terms = "elite_recode")

#Change all variables to factors (so we can see the separate effects at each level)
p_dem$pres=as.factor(p_dem$pres)
p_dem$pers_econ=as.factor(p_dem$pers_econ)
p_dem$pers_vio=as.factor(p_dem$pers_vio)
p_dem$count_econ_recode=as.factor(p_dem$count_econ_recode)
p_dem$count_vio_recode=as.factor(p_dem$count_vio_recode)
p_dem$politpart=as.factor(p_dem$politpart)
p_dem$elite_recode=as.factor(p_dem$elite_recode)

#Peru- reverse_index (separate effects)
summary(int_pres_index1_per <- lm(reverse_index~treat*pres+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_pres_index1_per, type = "pred", terms = "pres")
summary(int_persecon_index1_per <- lm(reverse_index~treat*pers_econ+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_persecon_index1_per, type = "pred", terms = "pers_econ")
summary(int_persvio_index1_per <- lm(reverse_index~treat*pers_vio+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_persvio_index1_per, type = "pred", terms = "pers_vio")
summary(int_countecon_index1_per <- lm(reverse_index~treat*count_econ_recode+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_countecon_index1_per, type = "pred", terms = "count_econ_recode")
summary(int_countvio_index1_per <- lm(reverse_index~treat*count_vio_recode+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_countvio_index1_per, type = "pred", terms = "count_vio_recode")
summary(int_polit_index1_per <- lm(reverse_index~treat*politpart+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_polit_index1_per, type = "pred", terms = "politpart")
summary(int_elite_index1_per <- lm(reverse_index~treat*elite_recode+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_elite_index1_per, type = "pred", terms = "elite_recode")

#Peru- forward_index (separate effects)
summary(int_pres_index2_per <- lm(forward_index~treat*pres+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_pres_index2_per, type = "pred", terms = "pres")
summary(int_persecon_index2_per <- lm(forward_index~treat*pers_econ+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_persecon_index2_per, type = "pred", terms = "pers_econ")
summary(int_persvio_index2_per <- lm(forward_index~treat*pers_vio+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_persvio_index2_per, type = "pred", terms = "pers_vio")
summary(int_countecon_index2_per <- lm(forward_index~treat*count_econ_recode+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_countecon_index2_per, type = "pred", terms = "count_econ_recode")
summary(int_countvio_index2_per <- lm(forward_index~treat*count_vio_recode+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_countvio_index2_per, type = "pred", terms = "count_vio_recode")
summary(int_polit_index2_per <- lm(forward_index~treat*politpart+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_polit_index2_per, type = "pred", terms = "politpart")
summary(int_elite_index2_per <- lm(forward_index~treat*elite_recode+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_elite_index2_per, type = "pred", terms = "elite_recode")

#Peru- claassen_index (separate effects)
summary(int_pres_index3_per <- lm(claassen_index~treat*pres+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_pres_index3_per, type = "pred", terms = "pres")
summary(int_persecon_index3_per <- lm(claassen_index~treat*pers_econ+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_persecon_index3_per, type = "pred", terms = "pers_econ")
summary(int_persvio_index3_per <- lm(claassen_index~treat*pers_vio+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_persvio_index3_per, type = "pred", terms = "pers_vio")
summary(int_countecon_index3_per <- lm(claassen_index~treat*count_econ_recode+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_countecon_index3_per, type = "pred", terms = "count_econ_recode")
summary(int_countvio_index3_per <- lm(claassen_index~treat*count_vio_recode+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_countvio_index3_per, type = "pred", terms = "count_vio_recode")
summary(int_polit_index3_per <- lm(claassen_index~treat*politpart+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_polit_index3_per, type = "pred", terms = "politpart")
summary(int_elite_index3_per <- lm(claassen_index~treat*elite_recode+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_elite_index3_per, type = "pred", terms = "elite_recode")

#Peru- main_index (separate effects)
summary(int_pres_main_per <- lm(main_index~treat*pres+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_pres_main_per, type = "pred", terms = "pres")
summary(int_persecon_main_per <- lm(main_index~treat*pers_econ+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_persecon_main_per, type = "pred", terms = "pers_econ")
summary(int_persvio_main_per <- lm(main_index~treat*pers_vio+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_persvio_main_per, type = "pred", terms = "pers_vio")
summary(int_countecon_main_per <- lm(main_index~treat*count_econ_recode+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_countecon_main_per, type = "pred", terms = "count_econ_recode")
summary(int_countvio_main_per <- lm(main_index~treat*count_vio_recode+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_countvio_main_per, type = "pred", terms = "count_vio_recode")
summary(int_polit_main_per <- lm(main_index~treat*politpart+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_polit_main_per, type = "pred", terms = "politpart")
summary(int_elite_main_per <- lm(main_index~treat*elite_recode+age+gender_n+income_n+ideo_1, data=p_dem))
plot_model(int_elite_main_per, type = "pred", terms = "elite_recode")
